In [6]:
import pandas as pd
import numpy as np

data = {
    "Order_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "City": ["Bengaluru", "Mysuru", "Bengaluru", "Delhi", "Mysuru",
             "Delhi", "Bengaluru", "Delhi", "Mysuru", "Bengaluru"],
    "Restaurant_Type": ["Cafe", "FastFood", "Cafe", "FineDining", "FastFood",
                        "Cafe", "FineDining", "FastFood", "Cafe", "FastFood"],
    "Order_Value": [450, 300, 700, 1200, 250, 500, 1500, 350, 800, 400],
    "Delivery_Minutes": [25, 35, 30, 50, 28, 40, 55, 32, 38, 22],
    "Rating": [4.5, 3.8, 4.8, 4.2, 3.5, 4.0, 4.7, 3.9, 4.6, 4.1],
    "Discount": [50, 20, 100, 150, 0, 50, 200, 30, 80, 40]
}

df = pd.DataFrame(data)
df.groupby("City")["Order_Value"].agg(["sum", "mean","count"])

            sum        mean  count
City
Bengaluru  3050  762.500000      4
Delhi      2050  683.333333      3
Mysuru     1350  450.000000      3

In [5]:
result = df.groupby(
    ["City", "Restaurant_Type"],
    as_index=False
).agg(
    Total_Order_Value=("Order_Value", "sum"),
    Avg_Delivery_Minutes=("Delivery_Minutes", "mean")
)

print(result)

        City Restaurant_Type  Total_Order_Value  Avg_Delivery_Minutes
0  Bengaluru            Cafe               1150                  27.5
1  Bengaluru        FastFood                400                  22.0
2  Bengaluru      FineDining               1500                  55.0
3      Delhi            Cafe                500                  40.0
4      Delhi        FastFood                350                  32.0
5      Delhi      FineDining               1200                  50.0
6     Mysuru            Cafe                800                  38.0
7     Mysuru        FastFood                550                  31.5

In [7]:
df.groupby("Restaurant_Type")["Rating"].agg(["mean","max","sum"])

                  mean  max   sum
Restaurant_Type
Cafe             4.475  4.8  17.9
FastFood         3.825  4.1  15.3
FineDining       4.450  4.7   8.9